# Site settings
title: Data Science Portfolio
description: Self-Lead Data Science Projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://OmarN-Mukhtar.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Omar Mukhtar
user_description: BSc of Economics, Management and Computer Science Student at Bocconi University
user_title: Data Science Student
email: omarmukhtar333@gmail.com
linkedin_username: Omar Mukhtar
github_username:  OmarN-Mukhtar

# Google-analytics
google-analytics:
  id: "G-G69DQL4MZ7"

exclude: ['package.json', 'src' , 'node_modules']
